import { Club } from './types';

export const CLUBS: Club[] = [
  // Premier League
  { id: '1', name: 'Manchester United', badge: 'https://media.api-sports.io/football/teams/33.png', fanCount: 125430, foundedYear: 1878, totalMatches: 4500, trophies: { league: 20, continental: 3, domestic: 12 }, valueRange: '€4.2B – €4.8B', coach: { name: 'Erik ten Hag', yearsAtClub: 2, philosophy: 'Attacking Football' }, tags: ['Historic Giant', 'Global Brand', 'Premier League Legends'], historySummary: 'One of the most successful clubs in English football history.' },
  { id: '2', name: 'Manchester City', badge: 'https://media.api-sports.io/football/teams/50.png', fanCount: 89450, foundedYear: 1880, totalMatches: 4100, trophies: { league: 10, continental: 1, domestic: 15 }, valueRange: '€4.2B – €4.8B', coach: { name: 'Pep Guardiola', yearsAtClub: 8, philosophy: 'Total Possession' }, tags: ['Modern Era Giant', 'Tactical Revolution', 'Global Network'], historySummary: 'A historic institution reborn into a tactical powerhouse.' },
  { id: '3', name: 'Liverpool', badge: 'https://media.api-sports.io/football/teams/40.png', fanCount: 95320, foundedYear: 1892, totalMatches: 4400, trophies: { league: 19, continental: 6, domestic: 17 }, valueRange: '€4.5B – €5.1B', coach: { name: 'Arne Slot', yearsAtClub: 1, philosophy: 'High Intensity' }, tags: ['European Heritage', 'Passionate Fanbase', 'Historic Stadium'], historySummary: 'A story of triumph and resilience, where every anthem sung at Anfield echoes through generations.' },
  { id: '4', name: 'Arsenal', badge: 'https://media.api-sports.io/football/teams/42.png', fanCount: 65200, foundedYear: 1886, totalMatches: 4000, trophies: { league: 13, continental: 0, domestic: 14 }, valueRange: '€3.5B – €4.1B', coach: { name: 'Mikel Arteta', yearsAtClub: 5, philosophy: 'Fluid Control' }, tags: ['Historic London', 'Attacking Tradition', 'Rebirth'], historySummary: 'From the Marble Halls of Highbury to the modern Emirates.' },
  { id: '5', name: 'Chelsea', badge: 'https://media.api-sports.io/football/teams/49.png', fanCount: 78200, foundedYear: 1905, totalMatches: 3900, trophies: { league: 6, continental: 2, domestic: 8 }, valueRange: '€3.2B – €3.8B', coach: { name: 'Enzo Maresca', yearsAtClub: 1, philosophy: 'Modern Football' }, tags: ['London Pride', 'European Champions', 'Youth Development'], historySummary: 'A modern powerhouse with a rich London heritage.' },
  { id: '6', name: 'Tottenham', badge: 'https://media.api-sports.io/football/teams/47.png', fanCount: 54300, foundedYear: 1882, totalMatches: 3800, trophies: { league: 2, continental: 0, domestic: 8 }, valueRange: '€2.8B – €3.2B', coach: { name: 'Ange Postecoglou', yearsAtClub: 2, philosophy: 'Attacking Football' }, tags: ['North London', 'Entertaining Football', 'New Era'], historySummary: 'Known for attacking football and passionate supporters.' },

  // La Liga
  { id: '7', name: 'Real Madrid', badge: 'https://media.api-sports.io/football/teams/541.png', fanCount: 125430, foundedYear: 1902, totalMatches: 4500, trophies: { league: 35, continental: 14, domestic: 19 }, valueRange: '€5.5B – €6.1B', coach: { name: 'Carlo Ancelotti', yearsAtClub: 4, philosophy: 'Adaptive Harmony' }, tags: ['Historic Giant', 'Continental King', 'Global Brand'], historySummary: 'More than a century of excellence, defining the pinnacle of European football.' },
  { id: '8', name: 'Barcelona', badge: 'https://media.api-sports.io/football/teams/529.png', fanCount: 110290, foundedYear: 1899, totalMatches: 4300, trophies: { league: 27, continental: 5, domestic: 31 }, valueRange: '€5.0B – €5.6B', coach: { name: 'Hansi Flick', yearsAtClub: 1, philosophy: 'Positional Dominance' }, tags: ['Youth Development', 'Cultural Icon', 'Unique Identity'], historySummary: 'Founded on a philosophy of artistic expression on the pitch.' },
  { id: '9', name: 'Atletico Madrid', badge: 'https://media.api-sports.io/football/teams/530.png', fanCount: 67200, foundedYear: 1903, totalMatches: 4100, trophies: { league: 11, continental: 3, domestic: 10 }, valueRange: '€3.8B – €4.2B', coach: { name: 'Diego Simeone', yearsAtClub: 12, philosophy: 'Defensive Strength' }, tags: ['La Liga Giants', 'European Contenders', 'Passionate Defense'], historySummary: 'Known for resilience, defensive strength, and passionate supporters.' },

  // Serie A
  { id: '10', name: 'Juventus', badge: 'https://media.api-sports.io/football/teams/496.png', fanCount: 78200, foundedYear: 1897, totalMatches: 4200, trophies: { league: 36, continental: 2, domestic: 14 }, valueRange: '€3.5B – €4.0B', coach: { name: 'Thiago Motta', yearsAtClub: 1, philosophy: 'Modern Football' }, tags: ['Italian Giants', 'Domestic Dominance', 'European History'], historySummary: 'The most successful club in Italian football history.' },
  { id: '11', name: 'AC Milan', badge: 'https://media.api-sports.io/football/teams/489.png', fanCount: 72100, foundedYear: 1899, totalMatches: 4100, trophies: { league: 19, continental: 7, domestic: 5 }, valueRange: '€3.2B – €3.8B', coach: { name: 'Paulo Fonseca', yearsAtClub: 1, philosophy: 'Attacking Football' }, tags: ['Italian Legends', 'European Royalty', 'Historic Club'], historySummary: 'One of the most successful clubs in European football history.' },
  { id: '12', name: 'Inter Milan', badge: 'https://media.api-sports.io/football/teams/505.png', fanCount: 69300, foundedYear: 1908, totalMatches: 4000, trophies: { league: 19, continental: 3, domestic: 8 }, valueRange: '€3.0B – €3.6B', coach: { name: 'Simone Inzaghi', yearsAtClub: 3, philosophy: 'Tactical Flexibility' }, tags: ['Italian Powerhouse', 'European History', 'Global Brand'], historySummary: 'A club with rich history and passionate global following.' },

  // Bundesliga
  { id: '13', name: 'Bayern Munich', badge: 'https://media.api-sports.io/football/teams/157.png', fanCount: 78100, foundedYear: 1900, totalMatches: 4200, trophies: { league: 33, continental: 6, domestic: 20 }, valueRange: '€4.0B – €4.6B', coach: { name: 'Vincent Kompany', yearsAtClub: 1, philosophy: 'Aggressive Structure' }, tags: ['Domestic Dominance', 'Efficient Power', 'Bavarian Pride'], historySummary: 'The undisputed heart of German football.' },
  { id: '14', name: 'Borussia Dortmund', badge: 'https://media.api-sports.io/football/teams/165.png', fanCount: 65200, foundedYear: 1909, totalMatches: 4000, trophies: { league: 8, continental: 1, domestic: 5 }, valueRange: '€2.5B – €3.0B', coach: { name: 'Nuri Sahin', yearsAtClub: 1, philosophy: 'Youth Development' }, tags: ['Yellow Wall', 'Youth Powerhouse', 'German Giants'], historySummary: 'Famous for their passionate fans and exciting attacking football.' },
  { id: '15', name: 'Bayer Leverkusen', badge: 'https://media.api-sports.io/football/teams/168.png', fanCount: 43200, foundedYear: 1904, totalMatches: 3800, trophies: { league: 1, continental: 0, domestic: 2 }, valueRange: '€1.8B – €2.2B', coach: { name: 'Xabi Alonso', yearsAtClub: 2, philosophy: 'Attacking Football' }, tags: ['German Rising', 'Undefeated Season', 'Modern Football'], historySummary: 'The team that made history with an undefeated Bundesliga season.' },

  // Ligue 1
  { id: '16', name: 'Paris Saint-Germain', badge: 'https://media.api-sports.io/football/teams/85.png', fanCount: 89200, foundedYear: 1970, totalMatches: 3800, trophies: { league: 11, continental: 0, domestic: 14 }, valueRange: '€3.8B – €4.2B', coach: { name: 'Luis Enrique', yearsAtClub: 2, philosophy: 'Attacking Football' }, tags: ['French Giants', 'Star Power', 'European Ambition'], historySummary: 'The dominant force in French football with global superstars.' },
  { id: '17', name: 'Olympique Marseille', badge: 'https://media.api-sports.io/football/teams/81.png', fanCount: 54300, foundedYear: 1899, totalMatches: 3900, trophies: { league: 9, continental: 1, domestic: 10 }, valueRange: '€2.2B – €2.6B', coach: { name: 'Roberto De Zerbi', yearsAtClub: 1, philosophy: 'Attacking Football' }, tags: ['French History', 'Passionate Fans', 'European Champions'], historySummary: 'The only French club to win the UEFA Champions League.' },
  { id: '18', name: 'AS Monaco', badge: 'https://media.api-sports.io/football/teams/91.png', fanCount: 32100, foundedYear: 1924, totalMatches: 3600, trophies: { league: 8, continental: 0, domestic: 5 }, valueRange: '€1.5B – €1.9B', coach: { name: 'Adi Hutter', yearsAtClub: 1, philosophy: 'Youth Development' }, tags: ['French Riviera', 'Talent Factory', 'European Nights'], historySummary: 'Known for developing young talents and playing attractive football.' },

  // Eredivisie
  { id: '19', name: 'Ajax', badge: 'https://media.api-sports.io/football/teams/194.png', fanCount: 51200, foundedYear: 1900, totalMatches: 4100, trophies: { league: 36, continental: 4, domestic: 20 }, valueRange: '€2.0B – €2.4B', coach: { name: 'Francesco Farioli', yearsAtClub: 1, philosophy: 'Total Football' }, tags: ['Dutch Legends', 'Youth Academy', 'European History'], historySummary: 'The pioneers of Total Football and one of Europe\'s most storied clubs.' },
  { id: '20', name: 'PSV Eindhoven', badge: 'https://media.api-sports.io/football/teams/197.png', fanCount: 43200, foundedYear: 1913, totalMatches: 3900, trophies: { league: 24, continental: 1, domestic: 11 }, valueRange: '€1.6B – €2.0B', coach: { name: 'Peter Bosz', yearsAtClub: 2, philosophy: 'Attacking Football' }, tags: ['Dutch Powerhouse', 'European History', 'Talent Development'], historySummary: 'One of the traditional "big three" clubs in the Netherlands.' },

  // Primeira Liga
  { id: '21', name: 'Benfica', badge: 'https://media.api-sports.io/football/teams/211.png', fanCount: 67800, foundedYear: 1904, totalMatches: 4200, trophies: { league: 38, continental: 2, domestic: 26 }, valueRange: '€2.5B – €2.9B', coach: { name: 'Roger Schmidt', yearsAtClub: 3, philosophy: 'Attacking Football' }, tags: ['Portuguese Giants', 'European History', 'Global Fanbase'], historySummary: 'One of the most supported clubs in the world with rich European history.' },
  { id: '22', name: 'Porto', badge: 'https://media.api-sports.io/football/teams/212.png', fanCount: 58900, foundedYear: 1893, totalMatches: 4100, trophies: { league: 30, continental: 2, domestic: 17 }, valueRange: '€2.3B – €2.7B', coach: { name: 'Sergio Conceicao', yearsAtClub: 7, philosophy: 'Winning Mentality' }, tags: ['Portuguese Powerhouse', 'European Champions', 'Tactical Discipline'], historySummary: 'Known for their European success and producing top talents.' },
  { id: '23', name: 'Sporting CP', badge: 'https://media.api-sports.io/football/teams/228.png', fanCount: 45600, foundedYear: 1906, totalMatches: 4000, trophies: { league: 19, continental: 0, domestic: 17 }, valueRange: '€1.8B – €2.2B', coach: { name: 'Ruben Amorim', yearsAtClub: 4, philosophy: 'Modern Football' }, tags: ['Portuguese Giants', 'Youth Academy', 'Tactical Innovation'], historySummary: 'Famous for their youth academy and recent domestic success.' },

  // Turkish Süper Lig
  { id: '24', name: 'Galatasaray', badge: 'https://media.api-sports.io/football/teams/213.png', fanCount: 54300, foundedYear: 1905, totalMatches: 4100, trophies: { league: 23, continental: 1, domestic: 18 }, valueRange: '€1.9B – €2.3B', coach: { name: 'Okan Buruk', yearsAtClub: 3, philosophy: 'Attacking Football' }, tags: ['Turkish Giants', 'European History', 'Passionate Fans'], historySummary: 'The first Turkish club to win a major European trophy.' },
  { id: '25', name: 'Fenerbahçe', badge: 'https://media.api-sports.io/football/teams/214.png', fanCount: 51200, foundedYear: 1907, totalMatches: 4000, trophies: { league: 19, continental: 0, domestic: 12 }, valueRange: '€1.7B – €2.1B', coach: { name: 'Jose Mourinho', yearsAtClub: 1, philosophy: 'Winning Mentality' }, tags: ['Turkish Powerhouse', 'Passionate Fanbase', 'European Ambition'], historySummary: 'One of Turkey\'s most successful and popular clubs.' },
  { id: '26', name: 'Besiktas', badge: 'https://media.api-sports.io/football/teams/215.png', fanCount: 43200, foundedYear: 1903, totalMatches: 3900, trophies: { league: 16, continental: 0, domestic: 10 }, valueRange: '€1.4B – €1.8B', coach: { name: 'Giovanni van Bronckhorst', yearsAtClub: 1, philosophy: 'Attacking Football' }, tags: ['Turkish Giants', 'Passionate Fans', 'Black Eagles'], historySummary: 'Known for their passionate fan base and competitive spirit.' },

  // MLS
  { id: '27', name: 'Inter Miami', badge: 'https://media.api-sports.io/football/teams/9568.png', fanCount: 65400, foundedYear: 2018, totalMatches: 1500, trophies: { league: 1, continental: 0, domestic: 1 }, valueRange: '€1.2B – €1.5B', coach: { name: 'Tata Martino', yearsAtClub: 2, philosophy: 'Attacking Football' }, tags: ['MLS Newcomers', 'Star Power', 'Global Brand'], historySummary: 'The new force in American soccer with global superstars.' },
  { id: '28', name: 'LA Galaxy', badge: 'https://media.api-sports.io/football/teams/1599.png', fanCount: 43200, foundedYear: 1995, totalMatches: 3500, trophies: { league: 5, continental: 0, domestic: 2 }, valueRange: '€1.0B – €1.3B', coach: { name: 'Greg Vanney', yearsAtClub: 4, philosophy: 'Attacking Football' }, tags: ['MLS Originals', 'Star History', 'West Coast'], historySummary: 'One of the most successful clubs in MLS history.' },
  { id: '29', name: 'LAFC', badge: 'https://media.api-sports.io/football/teams/1605.png', fanCount: 34500, foundedYear: 2014, totalMatches: 1200, trophies: { league: 1, continental: 0, domestic: 1 }, valueRange: '€0.9B – €1.1B', coach: { name: 'Steve Cherundolo', yearsAtClub: 3, philosophy: 'Modern Football' }, tags: ['MLS New Era', 'Black and Gold', 'West Coast'], historySummary: 'The newest powerhouse in American soccer.' },
  { id: '30', name: 'New York City FC', badge: 'https://media.api-sports.io/football/teams/1602.png', fanCount: 32100, foundedYear: 2013, totalMatches: 1100, trophies: { league: 1, continental: 0, domestic: 1 }, valueRange: '€0.8B – €1.0B', coach: { name: 'Nick Cushing', yearsAtClub: 3, philosophy: 'Attacking Football' }, tags: ['Big Apple', 'MLS Rising', 'Global Brand'], historySummary: 'The club representing the heart of New York City.' },
];

export const APP_GRADIENT = "linear-gradient(135deg, #22c55e 0%, #16a34a 100%)";